#### nympy task 1

In [4]:
import numpy as np

In [11]:
a = np.array([[1,6],
             [2,8],
             [3,11],
             [3,10],
             [1,7]])
print(a)

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]


In [12]:
mean_a = np.mean(a, axis = 0)
print(mean_a)

[2.  8.4]


In [15]:
a.shape

(5, 2)

#### nympy task 2

In [20]:
a_centered = a - mean_a

In [21]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

#### nympy task 3

In [32]:
a_centered.T[1]

array([-2.4, -0.4,  2.6,  1.6, -1.4])

In [31]:
a_centered[:,:1]

array([[-1.],
       [ 0.],
       [ 1.],
       [ 1.],
       [-1.]])

In [48]:
a_centered_sp = np.dot(a_centered.T[1], a_centered.T[0]) 
a_centered_sp / (a_centered.shape[0] - 1)

2.0

#### nympy task 4

In [44]:
np.cov(a.T)[0, 1]

2.0

In [45]:
np.cov(a.T)

array([[1. , 2. ],
       [2. , 4.3]])