In [1]:
import numpy as np

# #1

In [3]:
a = np.arange(12, 24)

# #2

In [16]:
a.reshape(2, 6)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [5]:
a.reshape(3, 4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [6]:
a.reshape(6, 2)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [8]:
a.reshape(4, 3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [10]:
a.reshape(12, 1)

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

# #3

In [11]:
a.reshape(-1, 2)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [12]:
a.reshape(-1, 3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [13]:
a.reshape(-1, 4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [15]:
a.reshape(3, -1)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# #4

Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

Нет

# #5

In [26]:
r = np.random.randn(3, 4)
r

array([[ 0.5804361 ,  0.74110053,  0.43027102,  1.06437406],
       [-0.29485388,  0.85863536,  0.04019047,  0.28289197],
       [-0.55183697, -2.36092725, -0.24548491,  1.16633344]])

In [28]:
rf = r.flatten()
rf

array([ 0.5804361 ,  0.74110053,  0.43027102,  1.06437406, -0.29485388,
        0.85863536,  0.04019047,  0.28289197, -0.55183697, -2.36092725,
       -0.24548491,  1.16633344])

# #6

In [29]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

# #7

In [34]:
b = np.linspace(20, 1, 10, endpoint = False, dtype = int)
b

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

Масивы а и b ничем не отличаются

# #8

In [44]:
a = np.zeros((3, 2))
b = np.ones((2, 2))
v = np.vstack([a, b])
v

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.]])

In [45]:
v.size

10

# #9

In [46]:
a = np.arange(0, 12)
A = a.reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [48]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [50]:
B = np.dot(A,At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

Число строк матрици, являющейся результатом умножений двух матриц, равно числу сток первой матрци, а число столбцов равно числу столбцов второй матрици.

In [52]:
np.linalg.det(B)

0.0

Определитель равен 0, значит найти обратную матрицу невозможно

# #10

In [56]:
np.random.seed(42)

# #11

Я не понял как создать массив "с" с заданными условиями, по этому просто создам массив от 0 до 16 для дальнейших заданий

In [78]:
c = np.linspace(0, 16, 16, endpoint = False, dtype = int)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

# #12

In [79]:
C = c.reshape((4, 4))
C

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [88]:
D = 10 * C + B
D

array([[  5,  24,  43,  62],
       [ 54, 100, 146, 192],
       [103, 176, 249, 322],
       [152, 252, 352, 452]])

In [90]:
np.linalg.matrix_rank(D)

2

In [91]:
np.linalg.det(D)

0.0

Определитель 0, найти обратную матрицу невозможно